### ISSUE TITLE
Host no work

### ISSUE THREAD

**Issue by Bibou1494** [matte-ek/BanchoMultiplayerBot#6]
People said me he can't change the map but i don't know why
![Capture2](https://github.com/matte-ek/BanchoMultiplayerBot/assets/132447113/c22803ce-6f6f-4c16-bc4c-833fecc79bea)
and i don't know why. It's because i am on 32 bit ?

**Comment by matte-ek** [comment]
This is most likely due to the `AutoHostRotate` behaviour not being enabled, if you go to the configure page of your lobby, is `AutoHostRotate` enabled in Behaviours? If it wasn't, make sure to enable that and then hit the "Restart" button in the Dashboard, for any lobbies you create in the future you can just select the auto host rotate preset while you create the lobby for this to be done automatically.

![image](https://github.com/matte-ek/BanchoMultiplayerBot/assets/49276951/13171bd5-b2e4-4cf1-8f36-28a88289b8aa)

**Comment by Bibou1494** [comment]
IT'S JUST THAT. I don't activate this so let me retry. If its just that I shoot me ...

**Comment by Bibou1494** [comment]
But can you change the readme file for remember to activate this

**Comment by Bibou1494** [comment]
Oh its possible to add a welcome message when people join ?

**Comment by matte-ek** [comment]
> But can you change the readme file for remember to activate this

I'm in the process of moving away from the readme, you can find information in the [wiki](https://github.com/matte-ek/BanchoMultiplayerBot/wiki/Usage) instead for now.



> Oh its possible to add a welcome message when people join ?

This is unfortunately not possible in the current version, however I this is something I could add.

**Comment by Bibou1494** [comment]
Ok thanks

**Comment by Bibou1494** [comment]
Ok I think is good thanks matte
